theme: jekyll-theme-minimal
title: Welcome to my portfolio !
description: Hi there, this is the place where you can find the skillset I posses and work I have done so far as a data analyst.
            
